---
title: "Project 2: Police Killings"
author: "Mac Phillips"
date: "2020-11-07"
output: html_document
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<div id="introduction-selecting-data" class="section level2">
<h2>Introduction: Selecting Data</h2>
<p>The dataset that I will be exploring is called “police_killings” and was accessed through the fivethirtyeight database.</p>
<pre class="r"><code>library(fivethirtyeight)</code></pre>
<pre><code>## Warning: package &#39;fivethirtyeight&#39; was built under R version 3.6.3</code></pre>
<pre><code>## Some larger datasets need to be installed separately, like senators and
## house_district_forecast. To install these, we recommend you install the
## fivethirtyeightdata package by running:
## install.packages(&#39;fivethirtyeightdata&#39;, repos =
## &#39;https://fivethirtyeightdata.github.io/drat/&#39;, type = &#39;source&#39;)</code></pre>
<pre class="r"><code>police_killings&lt;-police_killings
police_killings&lt;-na.omit(police_killings)
glimpse(police_killings)</code></pre>
<pre><code>## Rows: 410
## Columns: 34
## $ name                 &lt;chr&gt; &quot;A&#39;donte Washington&quot;, &quot;Aaron Rutledge&quot;, &quot;Aaron...
## $ age                  &lt;int&gt; 16, 27, 26, 25, 29, 29, 22, 35, 44, 31, 76, 40...
## $ gender               &lt;chr&gt; &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;Male&quot;...
## $ raceethnicity        &lt;chr&gt; &quot;Black&quot;, &quot;White&quot;, &quot;White&quot;, &quot;Hispanic/Latino&quot;, ...
## $ month                &lt;chr&gt; &quot;February&quot;, &quot;April&quot;, &quot;March&quot;, &quot;March&quot;, &quot;March&quot;...
## $ day                  &lt;int&gt; 23, 2, 14, 11, 19, 7, 27, 26, 28, 7, 26, 12, 2...
## $ year                 &lt;int&gt; 2015, 2015, 2015, 2015, 2015, 2015, 2015, 2015...
## $ streetaddress        &lt;chr&gt; &quot;Clearview Ln&quot;, &quot;300 block Iris Park Dr&quot;, &quot;22n...
## $ city                 &lt;chr&gt; &quot;Millbrook&quot;, &quot;Pineville&quot;, &quot;Kenosha&quot;, &quot;South Ga...
## $ state                &lt;chr&gt; &quot;AL&quot;, &quot;LA&quot;, &quot;WI&quot;, &quot;CA&quot;, &quot;OH&quot;, &quot;AZ&quot;, &quot;CA&quot;, &quot;CA&quot;...
## $ latitude             &lt;dbl&gt; 32.52958, 31.32174, 42.58356, 33.93930, 41.148...
## $ longitude            &lt;dbl&gt; -86.36283, -92.43486, -87.83571, -118.21946, -...
## $ state_fp             &lt;int&gt; 1, 22, 55, 6, 39, 4, 6, 6, 48, 26, 6, 6, 18, 1...
## $ county_fp            &lt;int&gt; 51, 79, 59, 37, 153, 13, 29, 37, 41, 81, 31, 5...
## $ tract_ce             &lt;int&gt; 30902, 11700, 1200, 535607, 530800, 111602, 70...
## $ geo_id               &lt;dbl&gt; 1051030902, 22079011700, 55059001200, 60375356...
## $ county_id            &lt;int&gt; 1051, 22079, 55059, 6037, 39153, 4013, 6029, 6...
## $ namelsad             &lt;chr&gt; &quot;Census Tract 309.02&quot;, &quot;Census Tract 117&quot;, &quot;Ce...
## $ lawenforcementagency &lt;chr&gt; &quot;Millbrook Police Department&quot;, &quot;Rapides Parish...
## $ cause                &lt;chr&gt; &quot;Gunshot&quot;, &quot;Gunshot&quot;, &quot;Gunshot&quot;, &quot;Gunshot&quot;, &quot;G...
## $ armed                &lt;chr&gt; &quot;No&quot;, &quot;No&quot;, &quot;No&quot;, &quot;Firearm&quot;, &quot;No&quot;, &quot;No&quot;, &quot;Fire...
## $ pop                  &lt;int&gt; 3779, 2769, 4079, 4343, 6809, 4682, 5027, 5238...
## $ share_white          &lt;dbl&gt; 60.5, 53.8, 73.8, 1.2, 92.5, 7.0, 50.8, 8.6, 1...
## $ share_black          &lt;dbl&gt; 30.5, 36.2, 7.7, 0.6, 1.4, 7.7, 0.3, 0.2, 17.7...
## $ share_hispanic       &lt;dbl&gt; 5.6, 0.5, 16.8, 98.8, 1.7, 79.0, 44.2, 84.1, 6...
## $ p_income             &lt;int&gt; 28375, 14678, 25286, 17194, 33954, 15523, 2594...
## $ h_income             &lt;int&gt; 51367, 27972, 45365, 48295, 68785, 20833, 5806...
## $ county_income        &lt;int&gt; 54766, 40930, 54930, 55909, 49669, 53596, 4855...
## $ comp_income          &lt;dbl&gt; 0.9379359, 0.6834107, 0.8258693, 0.8638144, 1....
## $ county_bucket        &lt;int&gt; 3, 2, 2, 3, 5, 1, 4, 4, 2, 3, 4, 5, 4, 3, 1, 3...
## $ nat_bucket           &lt;int&gt; 3, 1, 3, 3, 4, 1, 4, 4, 1, 2, 3, 5, 2, 2, 1, 3...
## $ pov                  &lt;dbl&gt; 14.1, 28.8, 14.6, 11.7, 1.9, 58.0, 17.2, 12.2,...
## $ urate                &lt;dbl&gt; 0.09768638, 0.06572379, 0.16629314, 0.12482727...
## $ college              &lt;dbl&gt; 0.16850951, 0.11140236, 0.14731227, 0.05013293...</code></pre>
<p>The dataset is a collection of data on individuals killed by police officers in the United States in 2015. After removing all na’s in the dataset, we are left with a list of 410 individuals, with data on their name, age in years, gender (binary), and race/ethnicity, as well as data on the census tract where the killing took place. This data includes population, poverty rates, unemployment rates, as well as the proportions of the populaton in the area that are white, black, and hispanic. I will be using this data to look for statistical bias when it comes to what kind of people are killed by police officers.</p>
</div>
<div id="manova" class="section level2">
<h2>MANOVA</h2>
<p>First, in order to explore the potential relationships existing within the dataset, I decided to conduct a MANOVA test, followed by ANOVA’s if significance was found, and finally post-hoc t-tests in order to pinpoint exactly where the significance lies in the dataset.</p>
<pre class="r"><code>man1&lt;-manova(cbind(age,share_white,share_black,share_hispanic,pov,urate)~raceethnicity, data=police_killings)
summary(man1)</code></pre>
<pre><code>##                Df  Pillai approx F num Df den Df    Pr(&gt;F)    
## raceethnicity   4 0.78226   16.329     24   1612 &lt; 2.2e-16 ***
## Residuals     405                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>##  Response age :
##                Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## raceethnicity   4   6168 1541.96  10.322 5.723e-08 ***
## Residuals     405  60500  149.38                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response share_white :
##                Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## raceethnicity   4 104972 26243.0  40.575 &lt; 2.2e-16 ***
## Residuals     405 261948   646.8                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response share_black :
##                Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## raceethnicity   4  74519 18629.8  41.069 &lt; 2.2e-16 ***
## Residuals     405 183719   453.6                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response share_hispanic :
##                Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## raceethnicity   4  68737 17184.2  38.347 &lt; 2.2e-16 ***
## Residuals     405 181489   448.1                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response pov :
##                Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## raceethnicity   4   6968 1742.04  10.446 4.618e-08 ***
## Residuals     405  67539  166.76                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response urate :
##                Df  Sum Sq  Mean Sq F value    Pr(&gt;F)    
## raceethnicity   4 0.16231 0.040578  8.8468 7.421e-07 ***
## Residuals     405 1.85764 0.004587                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>pairwise.t.test(police_killings$age, police_killings$raceethnicity, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  police_killings$age and police_killings$raceethnicity 
## 
##                 Asian/Pacific Islander Black   Hispanic/Latino Native American
## Black           0.077                  -       -               -              
## Hispanic/Latino 0.035                  0.377   -               -              
## Native American 0.072                  0.340   0.501           -              
## White           0.966                  7.4e-07 1.5e-06         0.037          
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(police_killings$share_white, police_killings$raceethnicity, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  police_killings$share_white and police_killings$raceethnicity 
## 
##                 Asian/Pacific Islander Black   Hispanic/Latino Native American
## Black           0.6943                 -       -               -              
## Hispanic/Latino 0.7280                 0.1113  -               -              
## Native American 0.8306                 0.6147  0.9876          -              
## White           8.1e-05                &lt; 2e-16 &lt; 2e-16         0.0053         
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(police_killings$share_black, police_killings$raceethnicity, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  police_killings$share_black and police_killings$raceethnicity 
## 
##                 Asian/Pacific Islander Black   Hispanic/Latino Native American
## Black           0.00069                -       -               -              
## Hispanic/Latino 0.41811                &lt; 2e-16 -               -              
## Native American 0.48682                0.00267 0.79287         -              
## White           0.44226                &lt; 2e-16 0.85070         0.74723        
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(police_killings$share_hispanic, police_killings$raceethnicity, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  police_killings$share_hispanic and police_killings$raceethnicity 
## 
##                 Asian/Pacific Islander Black  Hispanic/Latino Native American
## Black           0.2316                 -      -               -              
## Hispanic/Latino 0.0002                 &lt;2e-16 -               -              
## Native American 0.8012                 0.6303 0.0059          -              
## White           0.1622                 0.5988 &lt;2e-16          0.5470         
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(police_killings$pov, police_killings$raceethnicity, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  police_killings$pov and police_killings$raceethnicity 
## 
##                 Asian/Pacific Islander Black   Hispanic/Latino Native American
## Black           0.34885                -       -               -              
## Hispanic/Latino 0.48075                0.66307 -               -              
## Native American 0.02840                0.05125 0.04039         -              
## White           0.34446                9.4e-08 0.00018         0.00156        
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(police_killings$urate, police_killings$raceethnicity, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  police_killings$urate and police_killings$raceethnicity 
## 
##                 Asian/Pacific Islander Black   Hispanic/Latino Native American
## Black           0.622                  -       -               -              
## Hispanic/Latino 0.558                  0.020   -               -              
## Native American 0.217                  0.263   0.072           -              
## White           0.148                  4.2e-08 0.063           0.018          
## 
## P value adjustment method: none</code></pre>
<p>The MANOVA test found a high degree of significance (p&lt;2.2e-16), and all ANOVA tests also found a high degree of significance (highest p=7.421e-07). A number of p-values were found significant as a result of the post-hoc t-tests, but a total of 67 tests were conducted resulting in a high probability of a Type I error (96.78277% chance). The bonferroni-corrected cutoff was found to be 0.00074626, and with this cutoff there was significance between black and hispanic/latino vs white victims and their age, Asian/Pacific Islander, Black, and Hispanic/Latino vs White victims with a high share of white population, Asian/Pacific Islander, Hispanic/Latino, and White vs Black victims with a high share of black populatuon, Asian/Pacific ISlander, Black, and White vs Hispanic/Latino victims with a high share of Hispanic/Latino population, Black, Hispanic/Latino, and Native American vs White victims when high poverty was reported, and finally significance in White vs Black victims in areas with high rates of unemployment.</p>
<p>The sample sizes for the Asian/Pacific Islander and Native American groups were incredibly small (only 10 and 4 individuals, respectively), so it is highly unlikely that one or both of the groups are normally distributed across all variables. This violates the assumptions of the MANOVA test, so these results cannot be taken at face value. Some of the significant results may not be as significant as the MANOVA may suggest, or they may not be significant at all. Small sample sizes can thwart the accuracy of a multivariate test quickly.</p>
</div>
<div id="anovaf-statistic-randomization-test" class="section level2">
<h2>ANOVA/F statistic Randomization Test</h2>
<p>I then decided to examine the relationship between the age of victims and the share of black population in the area where they passed, as there was significance found in the differences of age between black and white victims.</p>
<pre class="r"><code>obs_F&lt;-16.329
Fs&lt;-replicate(5000,{
    new&lt;-police_killings%&gt;%mutate(share_black=sample(share_black))
    SSW&lt;- new%&gt;%group_by(age)%&gt;%summarize(SSW=sum((share_black-mean(share_black))^2))%&gt;%
        summarize(sum(SSW))%&gt;%pull
    SSB&lt;- new%&gt;%mutate(mean=mean(share_black))%&gt;%group_by(age)%&gt;%mutate(groupmean=mean(share_black))%&gt;%
        summarize(SSB=sum((mean-groupmean)^2))%&gt;%summarize(sum(SSB))%&gt;%pull
    (SSB/2)/(SSW/57)
})</code></pre>
<pre class="r"><code>mean(Fs&gt;obs_F)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>hist(Fs, prob=T)</code></pre>
<p><img src="public/project/project2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>The p-value was found to be 0, or at least very close to it, so we can reject the null hypothesis that there is no correlation between a deceased individual’s age and the proportion of black individuals in the immediate area where their death occurred. This suggests that where there is a high populaton of black individuals, the individuals killed by police are more likely to be older than where there is not a high population of black individuals.</p>
</div>
<div id="linear-regression-models" class="section level2">
<h2>Linear Regression Models</h2>
<p>I then decided to look more into potential relationships between age and other statistics. I decided to run a linear regression model between the interaction of the age of the victim and the poverty rate of where they were killed on the victimes race/ethnicity. First, I centered the ages and poverty rates, naming them ‘age_c’ and ‘pov_c’, and ran a linear regression with interaction on the variable ‘raceethnicity’.</p>
<pre class="r"><code>police_killings$age_c&lt;-police_killings$age-(mean(police_killings$age))
police_killings$pov_c&lt;-police_killings$pov-(mean(police_killings$pov))
racefit&lt;-lm(age_c*pov_c~raceethnicity, data=police_killings)
summary(racefit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = age_c * pov_c ~ raceethnicity, data = police_killings)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -779.54  -57.51   16.81   70.07  786.00 
## 
## Coefficients:
##                              Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)                    -33.22      54.20  -0.613   0.5404  
## raceethnicityBlack              13.17      56.33   0.234   0.8153  
## raceethnicityHispanic/Latino    18.96      58.41   0.325   0.7456  
## raceethnicityNative American  -167.86     101.41  -1.655   0.0986 .
## raceethnicityWhite              13.16      55.49   0.237   0.8127  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 171.4 on 405 degrees of freedom
## Multiple R-squared:  0.01116,    Adjusted R-squared:  0.001393 
## F-statistic: 1.143 on 4 and 405 DF,  p-value: 0.3359</code></pre>
<p>The Adjusted R-squared shows that 0.1393% of the variance in the model is explained by this linear regression model.
The interaction showed no significance, but the coefficients show that there are differences in slopes (y= victim Age, x=poverty rate) for each racial/ethnic group. Asian/Pacific Islander was the intercept at -33.22. The slope for Black individuals was 13.17 higher, the Hispanic/Latino slope was 18.96 higher, and the White slope was 13.16 higher (higher meaning “more positive” in this case). The slope for Native Americans was the most steeply negative, being 167.86 steeper than that for Asians/Pacific Islanders. This means that all of the slopes for each race/ethnicity were negative, so in all cases the individuals killed by police are generally older when the poverty rates are low and younger when the poverty rates are high.
These slopes were plotted on the graph below.</p>
<pre class="r"><code>ggplot(police_killings, aes(x=age_c,y=pov_c,group=raceethnicity))+geom_point(aes(color=raceethnicity))+geom_smooth(method=&quot;lm&quot;,se=F,fullrange=T,aes(color=raceethnicity))+theme(legend.position=c(.9,.45))+xlab(&quot;Poverty Centered&quot;)+ylab(&quot;Age Centered&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="public/project/project2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>library(sandwich)</code></pre>
<pre><code>## Warning: package &#39;sandwich&#39; was built under R version 3.6.3</code></pre>
<pre class="r"><code>library(lmtest)</code></pre>
<pre><code>## Warning: package &#39;lmtest&#39; was built under R version 3.6.3</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## Warning: package &#39;zoo&#39; was built under R version 3.6.3</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>resids&lt;-racefit$residuals; fitvals&lt;-racefit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="public/project/project2_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre class="r"><code>bptest(racefit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  racefit
## BP = 6.263, df = 4, p-value = 0.1803</code></pre>
<pre class="r"><code>shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.91609, p-value = 2.489e-14</code></pre>
<p>In order to check the assumptions of linearity and normality for the fit, I graphed the residuals against the fitted values for the model. The graph looks a little funky because there are only 5 categorial groups on the right side of the model, but linearity still looks ok. The graph did appear to fan out a bit on the right side, which sometimes indicates heteroskedasticity, however, a BP test confirmed that there was indeed homoskedasticity (p=0.1803). The data did not look normally distributed though, which was confirmed by a Shapiro-Wilk test (p=2.498e-14).</p>
<p>Regardless, I decided to compute results using robust standard errors with a coeftest.</p>
<pre class="r"><code>coeftest(racefit, vcov = vcovHC(racefit))[,1:2]</code></pre>
<pre><code>##                                Estimate Std. Error
## (Intercept)                   -33.21542   29.75247
## raceethnicityBlack             13.16675   34.59170
## raceethnicityHispanic/Latino   18.96121   33.03584
## raceethnicityNative American -167.85639  122.58626
## raceethnicityWhite             13.15598   32.05070</code></pre>
<p>The robust standard errors did not change the coefficients very much at all, maybe by a thousandth of a decimal in most cases. However, the standard error values were noticeably lower than in the original model, except for among Native Americans where the standard error rose from 101.41 to 122.586. The change in standard errors not changin the coefficients by much is interesting, suggesting that the original model was fairly strong in its accuracy already.</p>
<p>I then computed more standard errors by bootstrapping from residuals. I used a seed (1234) for consistancy’s sake.</p>
<pre class="r"><code>#Bootstrapped Std Err from Residuals
set.seed(1234)
fit&lt;-lm(age_c*pov_c~raceethnicity,data=police_killings) #fit model
resids&lt;-fit$residuals #save residuals
fitted&lt;-fit$fitted.values #save yhats
resid_resamp&lt;-replicate(5000,{
   new_resids&lt;-sample(resids,replace=TRUE) #resample resids w/ replacement
   police_killings$new_y&lt;-fitted+new_resids #add new resids to yhats to get new &quot;data&quot;
   fit&lt;-lm(new_y~raceethnicity,data=police_killings) #refit model
   coef(fit) #save coefficient estimates (b0, b1, etc)
})
resid_resamp%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) raceethnicityBlack raceethnicityHispanic/Latino
## 1    54.62827           56.56367                     58.76031
##   raceethnicityNative American raceethnicityWhite
## 1                     101.2449           55.96137</code></pre>
<p>The bootstrapped standard errors were much closer to those originally found by the first linear fit model than the robust standard errors. In fact, all of the bootstrapped standard errors were within one unit of the original standard errors from the linear fit model. Similarly, the p-values from the bootstrapped sample were nearly identical to those found from the original linear fit model, showing no significant differences between the slopes measured. Because the SE’s are larger overall in the linear fit model and bootstrapped model and there are marginal differences between the two, I would be comfortable using either group in drawing conclusions concerning this particular linear relationship.</p>
</div>
<div id="logistic-regression-models" class="section level2">
<h2>Logistic Regression Models</h2>
<p>After running the linear regression model, I decided to run some logistic regressions against the one dichotomous variable in the dataset: the binary gender of the deceased individuals. I ran the first logistic regression against age and race/ethnicity. I started by making a new variable called ‘y’ that corresponds with the gender variable, 1=male and 0=female.</p>
<pre class="r"><code>library(lmtest)
police_killings&lt;-police_killings%&gt;%mutate(y=ifelse(gender==&quot;Male&quot;,1,0))
logfit&lt;-glm(y~age+raceethnicity,data=police_killings,family=&quot;binomial&quot;)
coeftest(logfit)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                                Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)                  1.6694e+00 1.3074e+00  1.2769   0.2016
## age                          1.3131e-02 1.9499e-02  0.6734   0.5007
## raceethnicityBlack           7.2232e-01 1.1334e+00  0.6373   0.5239
## raceethnicityHispanic/Latino 2.0280e+00 1.4690e+00  1.3806   0.1674
## raceethnicityNative American 1.4533e+01 1.1996e+03  0.0121   0.9903
## raceethnicityWhite           7.0112e-01 1.0997e+00  0.6375   0.5238</code></pre>
<pre class="r"><code>probs&lt;-predict(logfit,type=&quot;response&quot;)
table(predict=as.numeric(probs&gt;.5),truth=police_killings$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     1    20 390 410
##     Sum  20 390 410</code></pre>
<pre class="r"><code>table(predict=as.numeric(probs&gt;.9),truth=police_killings$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0     0   7   7
##     1    20 383 403
##     Sum  20 390 410</code></pre>
<p>The coefficients from the logistic regression shows that when a victim is Asian/Pacific Islander, their log-odds of being male are 1.6694, or and odds of about 5.30898. As age increases, log odds increases by 1.3131e-02, making odds of being male increase by 1.0132 per year of age. If an individual is black, log-odds rise by 7.2232e-01 (odds=2.0592), if they are Hispanic/Latino log-odds rise by 2.0280 (odds=7.5989), if they are Native American log-odds rise by 14.533 (odds=2.04928e6), and if they are white, log-odds rise by 7.0112e-01 (odds=2.016). This means that if an individual is Native American, they were most certainly male. Behind that group, Hispanic/Latino victims are most likely to be male, followed by black victims, whites, and finally Asians/Pacific Islanders. Overall though, males are certainly more prevalent in the dataset compared to females.
I computed a confusion matrix and decided to use .9 as a cutoff, as lower values showed 100% accuracy, which was not very interesting. From that confusion matrix, I found that Accuracy=0.93415, Sensitivity=0.95037, Specificity=0.0, Precision=0.98205, and AUC=0.6. Most of these values are great, except for Specificity, which means that at this cutoff our model cannot accurately predict when a deceased individual is female based soleley on age and race/ethnicity. Additionally, the AUC is not great, but it is also not necessarily bad.</p>
<p>Next, I decided to plot the ROC and compute AUC for the probabilities vs the dichotomous gender variable.</p>
<pre class="r"><code>library(plotROC)</code></pre>
<pre><code>## Warning: package &#39;plotROC&#39; was built under R version 3.6.3</code></pre>
<pre class="r"><code>ROCplot&lt;-ggplot(police_killings)+geom_roc(aes(d=y,m=probs), n.cuts=0)
ROCplot</code></pre>
<p><img src="public/project/project2_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.5966667</code></pre>
<p>Again, the AUC does not look awesome (5.96667) but it could certainly be worse!</p>
<div id="random-sub-sampling-and-lasso" class="section level4">
<h4>Random Sub-Sampling and LASSO</h4>
<p>Next, I decided to run a random sub-sample cross-validation on the dataset, using the mutated ‘y’ variable against (almost) all of the numeric variables in the dataset. (The ‘class_diag’ function was included in the r setup chunk.)</p>
<pre class="r"><code>bigfit&lt;-glm(y~age+pop+share_white+share_black+share_hispanic+p_income+h_income+county_income+comp_income+pov+urate+college, data=police_killings, family=&quot;binomial&quot;)
prob&lt;-predict(bigfit,type=&quot;response&quot;)
pred&lt;-ifelse(prob&gt;.5,1,0)
table(prediction=pred, truth=police_killings$y) %&gt;% addmargins</code></pre>
<pre><code>##           truth
## prediction   0   1 Sum
##        0     1   0   1
##        1    19 390 409
##        Sum  20 390 410</code></pre>
<p>The internal classification diagnostics show that the model has 95.366% Accuracy in predicting gender correctly(Acc=0.953658), 100% Sensitivity in correctly predicting females (TPR=1.00), 93.35% Specificity in correctly predicting males (TNR=0.953545), and 5% Precision as only 1/20 of the femaels in the dataset were predicted correctly.</p>
<pre class="r"><code>acc&lt;-data.frame()
for(i in 1:nrow(police_killings)){
    ## Create training and test sets
    train&lt;-police_killings[-i,] #all but observation/row i
    test&lt;-police_killings[i,] #just observation/row i
    truth&lt;-test$y
    ## Fit model on training set (all rows but row i)
    fit&lt;-glm(y~age+pop+share_white+share_black+share_hispanic+p_income+h_income+county_income+comp_income+pov+urate+college,data=train,family=&quot;binomial&quot;)
    ## Test model on remaning datapoint (row i)
    prob&lt;-predict(fit,newdata = test, type=&quot;response&quot;)
    ## Save predicted probability and truth label for point i
    acc&lt;-rbind(acc,c(prob,truth))
    names(acc)&lt;-c(&quot;prob&quot;,&quot;truth&quot;)
}
class_diag(acc$prob,acc$truth)</code></pre>
<pre><code>##         acc      sens spec      ppv        f1       auc
## 1 0.9487805 0.9948718 0.05 0.953317 0.9736512 0.5714103</code></pre>
<p>The AUC of 0.5714 is not great for the soundness of the predictors for gender in this dataset. It is likely low in part to the low specificity of the model (0.05), which means that the model can only correctly predict when a victim is female from all of the numeric variables 5% of the time. The rest of the statistics are so high (Accuracy=94.878% were predicted correctly, Sensitivity=99.487% of males were predicted correctly, Precision=95.33% of predicted males were actually males) likely because there are only 7 females in the datset, so the model correctly predicted that each individual would be male essentially by chance. This is not great if we want to be able to predict whether a victim is male or female, as the model could in theory spit out a male prediction for every individual and appear to be accurate when it is actually failing to accomplish its purpose. Compared to the internal classification diagnostics, all of the coefficients are similar except for precision and specificity, which seem to be flipped.</p>
<p>In order to explore the model further, I performed a LASSO regression on all of the numeric variables used in the above Cross-Validation in order to see which variables may be the most effective predictors.</p>
<pre class="r"><code>library(glmnet)</code></pre>
<pre><code>## Warning: package &#39;glmnet&#39; was built under R version 3.6.3</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 4.0-2</code></pre>
<pre class="r"><code>y&lt;-as.matrix(police_killings$y)
x&lt;-police_killings%&gt;%select(age,pop,share_white,share_black,share_hispanic,p_income,h_income,county_income,comp_income,pov,urate,college)%&gt;%mutate_all(scale)%&gt;%as.matrix
cv&lt;-cv.glmnet(x,y)
lasso1&lt;-glmnet(x,y,lambda=cv$lambda.1se)
coef(lasso1)</code></pre>
<pre><code>## 13 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                       s0
## (Intercept)    0.9512195
## age            0.0000000
## pop            .        
## share_white    .        
## share_black    .        
## share_hispanic .        
## p_income       .        
## h_income       .        
## county_income  .        
## comp_income    .        
## pov            .        
## urate          .        
## college        .</code></pre>
<pre class="r"><code>acc&lt;-data.frame()
for(i in 1:nrow(police_killings)){
    ## Create training and test sets
    train&lt;-police_killings[-i,] #all but observation/row i
    test&lt;-police_killings[i,] #just observation/row i
    truth&lt;-test$y
    ## Fit model on training set (all rows but row i)
    fit&lt;-glm(y~age,data=train,family=&quot;binomial&quot;)
    ## Test model on remaning datapoint (row i)
    prob&lt;-predict(fit,newdata = test, type=&quot;response&quot;)
    ## Save predicted probability and truth label for point i
    acc&lt;-rbind(acc,c(prob,truth))
    names(acc)&lt;-c(&quot;prob&quot;,&quot;truth&quot;)
}
class_diag(acc$prob,acc$truth)</code></pre>
<pre><code>##         acc sens spec       ppv    f1       auc
## 1 0.9512195    1    0 0.9512195 0.975 0.2405128</code></pre>
<p>The only predictor identified by the LASSO regression was victim age. I ran the same CV on the dataset, this time only predicting gender from age, and found an even worse AUC than before. Additionally, this Specificity was 0 meaning that the model predicted that an individual would be female exactly zero times. This means that there is likely no reliable way to predict a victim’s gender from the numeric variables given in this dataset.</p>
</div>
</div>
<div id="final-thoughts-and-conclusions" class="section level2">
<h2>Final Thoughts and Conclusions</h2>
<p>A major issue that I had with this data was that only deceased individuals were represented. There was no representation of those who are confronted by police and survive, are arrested, or are let free. Here, there are only the tragically departed, and for this reason I debated examining this dataset in the first place. Clearly, the subject of this project is incredibly delicate, and it certainly unsavory to speak of deceased individuals as merely datapoints and figures. I aimed to treat the departed with the upmost respect, therefore I did not choose to examine this dataset in an effort to make any sort of political statement or to suggest any sort of difinitive relationship between all individuals killed by the police all of the time.</p>
<p>I hope that in the future, more studies can be done on similar data so that we may learn more about ourselves as a society, as Americans, and as human beings. In the meantime, I hope we all continue to struggle against human nature, thrash against the status quo, and strive to heal the wounds that mar the face of our nation.</p>
</div>
